[package]
name = "monotron"
version = "0.1.0"
edition = "2021"

[dependencies]
structopt = "0.3"
chrono = "0.4"
xid = "1.0"
url = "2.2"
tokio = { version = "1", features = ["full"] }
tokio-postgres = "0.7.5"