
replicaCount: 1

image:
  repository: gcr.io/treno-staging/monotron
  pullPolicy: Always

app:
  secrets: monotron-secrets
  config: monotron-config

monotron:
  environ: staging
  component: monotron
  addr: :3030
  enableProfiling: true
  databaseDSN: ""
  credentials:
    apiKey: root
    apiSecret: secret

securityContext:
  capabilities:
    drop:
    - ALL
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: NodePort
  port: 3030
