#!/usr/bin/env bash

set -eo pipefail

# where am i?
me="$0"
me_home=$(dirname "$0")
me_home=$(cd "$me_home" && pwd)

# deps
. "$me_home/_lib.sh"

database="monotron_$ENVIRON"
echo "Cycling database: $database"

psql -U postgres -h 127.0.0.1 -c "drop database if exists $database" > /dev/null
psql -U postgres -h 127.0.0.1 -c "create database $database" > /dev/null
