#!/usr/bin/env bash

set -eo pipefail

# where am i?
me="$0"
me_home=$(dirname "$0")
me_home=$(cd "$me_home" && pwd)

# project
project_home=$(cd "$me_home/.." && pwd)

# deps
. "$me_home/_lib.sh"

# defaults
component=monotron
image_tag=$ENVIRON

# parse arguments
args=$(getopt s:t:S: $*)
set -- $args
for i; do
  case "$i"
  in
    -s)
      extra_args="$extra_args --set-string $2"; shift;
      shift;;
    -t)
      image_tag="$2"; shift;
      shift;;
    -S) # read secrets from stdin
      secrets_url="$2"; shift;
      extra_args="$extra_args -f -";
      shift;;
    --)
      shift;
      break;;
  esac
done

if [ -z "$image_tag" ]; then
  echo "*** No image tag specified; use: -t <tag>"
  exit 1
fi
if [ -z "$1" ]; then
  echo "No values files provided; use: $0 <values> [values ...]"
  exit 1
fi
for arg in $@; do
  extra_args="$extra_args -f $arg";
  shift;
done

# where are we
cluster="$(kubectl config current-context)"
echo -e "You are on branch:\n    ➤ $(git branch --show-current)"
echo
echo -e "You are about to install $component:$image_tag here:\n    ➤ $cluster"

echo
read -p "Really deploy? [y/N] " -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
  if [ -n "$secrets_url" ]; then
    keybase fs read "$secrets_url" | helm upgrade -i --set-string image.tag=$image_tag $extra_args "$component" "$project_home/deploy/k8s/$component"
  else
    helm upgrade -i --set-string image.tag=$image_tag $extra_args "$component" "$project_home/deploy/k8s/$component"
  fi
fi
