#!/usr/bin/env bash

set -eo pipefail

# where am i?
me="$0"
me_home=$(dirname "$0")
me_home=$(cd "$me_home" && pwd)

# project
project_home=$(cd "$me_home/.." && pwd)

# deps
. "$me_home/_lib.sh"

# defaults
component=monotron
image_tag=$ENVIRON

# parse arguments
args=$(getopt s:t: $*)
set -- $args
for i; do
  case "$i"
  in
    -s)
      extra_args="$extra_args --set-string $2"; shift;
      shift;;
    -t)
      image_tag="$2"; shift;
      shift;;
    --)
      shift;
      break;;
  esac
done

if [ ! -z "$1" ]; then
  values="$1"
  shift
else
  echo "Usage: deploy <values>"
  exit 1
fi

if [ -z "$image_tag" ]; then
  echo "*** No image tag specified; use: -t <tag>"
  exit 1
fi

# where are we
cluster="$(kubectl config current-context)"
echo -e "You are about to install $component:$image_tag here:\n\n    ➤ $cluster"

echo
read -p "Really deploy? [y/N] " -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
  helm upgrade -i -f "$values" --set-string image.tag=$image_tag $extra_args "$component" "$project_home/deploy/k8s/$component"
fi
