#!/usr/bin/env bash

set -eo pipefail

# where am i?
me="$0"
me_home=$(dirname "$0")
me_home=$(cd "$me_home" && pwd)

# project
project_home=$(cd "$me_home/.." && pwd)

# deps
. "$me_home/_lib.sh"

# defaults
image_name=monotron
context_name=brian
image_host=docker.io
version=$VERSION

# parse arguments
args=$(getopt p:v: $*)
set -- $args
for i; do
  case "$i"
  in
    -p)
      context_name="$2"; shift;
      shift;;
    -v)
      version="$2"; shift;
      shift;;
    --)
      shift; break;;
  esac
done

# validate our state
assert_flag "$context_name" "No context specified for repo; use: -p <project_id>"
assert_flag "$version" "No version specified; use: -v <version>"

# configure
image_url=$image_host/$context_name/$image_name

# build our container
docker build \
  -t "$image_name:latest" \
  -t "$image_name:$version" \
  -t "$image_url:latest" \
  -t "$image_url:$version" \
  -f "$project_home/deploy/build/Dockerfile" \
  "$project_home"

# push to our repo
docker push "$image_url:latest"
docker push "$image_url:$version"
