#!/usr/bin/env bash

set -eo pipefail

# where am i?
me="$0"
me_home=$(dirname "$0")
me_home=$(cd "$me_home" && pwd)

# project
project_home=$(cd "$me_home/.." && pwd)

# environment
export ENVIRON=integration
export DB_DSN=postgresql://postgres@localhost/monotron_$ENVIRON?connect_timeout=5
export ROOT_API_KEY=testapi
export ROOT_API_SECRET=secret123

# tools
export REDOCLY=${REDOCLY:=redocly}

# deps
. "$me_home/_lib.sh"

# defaults
component=monotron
hostname=localhost
exec_cmd="$project_home/target/debug/monotron"
test_root="$project_home/test/api"

# parse arguments
args=$(getopt D: $*)
set -- $args
for i; do
  case "$i"
  in
    -D)
      docs_root="$2"; shift;
      extra_flags=$(append_flags "$extra_flags" "--gendoc --doc:type openapi --doc:include-http --doc:format-entities --doc:output $docs_root");
      shift;;
    --)
      shift;
      break;;
  esac
done

# build the target
(cd "$project_home/" && cargo build)
# cycledb
$me_home/cycledb
# packages from the command line
packages=$*

# run integration tests
if [ ! -z "$packages" ]; then \
  $INSTAUNIT $extra_flags \
    --base-url "http://$hostname:3030/" \
    --http:redirects 0 \
    --exec "${exec_cmd}" \
    --await "http://$hostname:3030/v1" \
    $services $(echo "$packages" | tr ',' ' ' | perl -pe 's/\s+/\n/g' | xargs -I '%' echo "$test_root/%.yml" | perl -pe 's/\n/ /g')
else
  $INSTAUNIT $extra_flags \
    --base-url "http://$hostname:3030/" \
    --http:redirects 0 \
    --exec "${exec_cmd}" \
    --await "http://$hostname:3030/v1" \
    $service $(find "$test_root" -name '*.yml' -and \! -name '*-service.yml' | sort)
fi

if [ ! -z "$docs_root" ]; then
  which $REDOCLY &> /dev/null || (vs_echo "You must install Redocly; try something like:\n\t\$ npm i -g @redocly/cli@latest\nor download it from:\n\t➡ https://github.com/Redocly/redocly-cli" && exit 1)
  $REDOCLY build-docs -o "$docs_root/service.html" "$docs_root/service.json"
fi
