#!/usr/bin/env bash

set -eo pipefail

# where am i?
me="$0"
me_home=$(dirname "$0")
me_home=$(cd "$me_home" && pwd)

# deps
. "$me_home/_lib.sh"

database="monotron_$ENVIRON"

for table in $@; do
  echo "Truncate: $database.$table"
  psql -U postgres -h 127.0.0.1 -c "truncate $table cascade" $database > /dev/null || echo "Skip"
done
