apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.app.secrets }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  databaseDSN: {{ required ".Values.monotron.databaseDSN entry required!" .Values.monotron.databaseDSN | b64enc | quote }}
  rootAPIKey: {{ required ".Values.monotron.credentials.apiKey entry required!" .Values.monotron.credentials.apiKey | b64enc | quote }}
  rootAPISecret: {{ required ".Values.monotron.credentials.apiSecret entry required!" .Values.monotron.credentials.apiSecret | b64enc | quote }}
